### ISSUE TITLE
Dreamcast redump reversal

### ISSUE THREAD

**Issue by treloret** [putnam/binmerge#15] opened 2023-07-13 11:36 UTC
Initial tests show that a redump dreamcast .cue file has 2 remarks in it in the original cue file:

REM SINGLE-DENSITY AREA
before the first 2 tracks and
REM HIGH-DENSITY AREA
between track 2 and 3, track 3 and up being the bulk of the data

can there be a commandline switch added to -fixdccue or some such?

**Comment by treloret** [comment] 2023-07-13 11:50
Ok, not fluent in python, but seem to have come up with something.
[binmerge.txt](https://github.com/putnam/binmerge/files/12039037/binmerge.txt)

**Comment by putnam** [comment] 2023-07-13 18:34
Right, so the issue is bringing back the remarks when reversing from merged DC images back to the originals?

Is the single-density area always exactly two tracks? I'm poking around on Redump to confirm but it looks like it.

**Comment by treloret** [comment] 2023-07-13 20:52
REM lines are only useful for the one who put them there, any other program should ignore them, keeping the REM lines would be the better solution. I'm only testing by verifying that both ways they come out with the same md5.

**Comment by treloret** [comment] 2023-07-13 21:08
Action Replay CDX - Demo Version (UK) (Unl) has different remarks:

REM SESSION 01
FILE "Action Replay CDX - Demo Version (UK) (Unl) (Track 1).bin" BINARY
  TRACK 01 AUDIO
    INDEX 01 00:00:00
REM SESSION 02
FILE "Action Replay CDX - Demo Version (UK) (Unl) (Track 2).bin" BINARY
  TRACK 02 MODE2/2352
    INDEX 01 00:00:00

**Comment by treloret** [comment] 2023-07-13 21:14
Just checked #-C and those seem to be the 2 variants, the SINGLE DENSITY/HIGH DENSITY remarks for regular games, and SESSION 01/SESSION 02 for (unl) games (SESSION 2 remark seems to be just before the last track instead of after track 2)

**Comment by treloret** [comment] 2023-07-13 21:44
Just checked 1468 cue files if the 9th line was HIGH DENSITY, 79 didn't fit that bill, 69 of those where marked (unl), and then there's these 10:
Checkicco no Miru CD (Japan).cue
D2 - Original Sound Track (Japan) (Disc 2) (MilCD).cue
Debug Indie Sampler 1 (UK).cue
Debug Indie Sampler 2 (UK).cue
dps - Heartbreak Diary (Japan).cue
Hang the DJ (Japan).cue
Himitsu - Original Sound Track (Japan).cue
Kita e. White Illuminaton - Pure Songs and Pictures (Japan).cue
Snappers - 09 Chairs (Japan).cue
Space Channel 5 Theme Music - Mexican Flyer (Japan).cue

Those are SESSION1/2 too, but the only anomaly I see now is that some OSTs like Hang the DJ start with a CATALOG and have ISRC tags per track i.e.:

CATALOG 4535506800022
REM SESSION 01
FILE "Hang the DJ (Japan) (Track 1).bin" BINARY
  TRACK 01 AUDIO
    ISRC JPD609900923
    INDEX 01 00:00:00
FILE "Hang the DJ (Japan) (Track 2).bin" BINARY
  TRACK 02 AUDIO
    ISRC JPD609900924
    INDEX 00 00:00:00
    INDEX 01 00:01:43
FILE "Hang the DJ (Japan) (Track 3).bin" BINARY
  TRACK 03 AUDIO
    ISRC JPD609900925
    INDEX 00 00:00:00
    INDEX 01 00:01:42
REM SESSION 02
FILE "Hang the DJ (Japan) (Track 4).bin" BINARY
  TRACK 04 MODE2/2352
    INDEX 01 00:00:00

**Comment by treloret** [comment] 2023-07-13 21:52
https://en.wikipedia.org/wiki/Cue_sheet_(computing) has those listed under CD-Text and other metadata commands

**Comment by treloret** [comment] 2023-07-13 21:54
But now it defeats my original purpose of being able to binmerge -> chd and reverting for scanning without needing an external cue-source.

**Comment by putnam** [comment] 2023-07-13 22:18
Yes, programs should ignore "REM" lines, just like they should parse cues
the correct way to begin with. But if programs all read cues properly we
wouldn't need this program. We want to be sure keeping the REM lines will
still work in the software people actually run binmerge for

**Comment by treloret** [comment] 2023-07-14 07:40
So in hindsight, my version is 95% best, since the user specifically needs use a commandline argument that it wants a redump compatible .cue file for dreamcast, and doesn't require the original file. Just needs to mention to the user that it's not a panacea.

**Comment by putnam** [comment] 2023-07-14 08:05
Honestly I've never loved the idea of reversing the cue sheets anyway. Cue sheets take up no space. What if we just save the old cue sheet as .origcue or similar and restore it if the revert is requested?

**Comment by treloret** [comment] 2023-07-14 09:42
Reason to binmerge is often times for single use to make it compatible for the programs that can't handle them properly. Reason to reverse the process is because you've gotten your hands on the merged one, or just uncompressed a chd file, for verification purposes, so chances are likely that the .origcue wouldn't be available then.

**Comment by putnam** [comment] 2023-09-08 10:07
Sorry I faded out on this one. 

When binmerge merges an image it has to synthesize a whole new cuesheet, since it has to calculate new timestamp offsets for all the individual tracks within the single bin file. The challenge is accurately storing all the REM lines in such a way that they can be put into the right place when you try to reverse it. Same thing for the ISRC tags.

Based on your examples you provided there seems to be a wide variety of metadata tags in use even within the Dreamcast library and they vary in style from disc to disc. Since the metadata tags are not tied to a specific track and can appear anywhere, I think the only way to bring them back accurately would be to store them in some coded way, I guess using REM lines to hide them at the bottom of the file.

> Reason to reverse the process is because you've gotten your hands on the merged one, or just uncompressed a chd file, for verification purposes, so chances are likely that the .origcue wouldn't be available then.

So really herein lies the problem, where you sourced it from.

For what it's worth, Redump provides a zip of all the correct cuesheets for a given system. You can download the entire cuesheet pack and extract the cue you need here: http://redump.org/downloads/

I really don't love storing the tags in a gross way in the file to back them up, and it would only work in the case where the thing was merged specifically by binmerge anyway. I wonder if the best solution is just to provide additional documentation with --split that it will create functional cuesheets, but they won't match Redump as they will not contain comments and metadata tags, then link to the Redump download page?

**Closed** 2024-01-31 20:26 UTC
